title: Laura Hannah
logo: "https://github.com/lhannahh/lhannahh.github.io/blob/main/Linked%20In%20Headshot%202025.jpg"
description: Welcome to Laura Hannah's Data Science Portfolio
show_downloads: false
theme: jekyll-theme-minimal

