title: Laura Hannah
logo: "https://raw.githubusercontent.com/lhannahh/lhannahh.github.io/main/Linked%20In%20Headshot%202025.jpg"
description: Welcome to my Portfolio!
show_downloads: true
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
    values:
      css: "assets/css/custom.css"
